# Generated by Django 5.2.6 on 2025-10-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('zipcode', models.CharField(max_length=64)),
            ],
        ),
    ]
